### ISSUE TITLE
Nombres de tablas

### ISSUE THREAD

**Issue by davidtavarez** [nromero125/glucolog#12]
Los nombres de las tablas están en spanglish.
![screen shot 2018-03-10 at 10 34 48 am](https://user-images.githubusercontent.com/337107/37243395-ef627586-244e-11e8-94e6-7756d3b3b811.png)

**Comment by nromero125** [comment]
Fixed 
![screenshot from 2018-03-10 11-35-39](https://user-images.githubusercontent.com/10222142/37243905-69fe0172-2457-11e8-8369-c61cbda5228d.png)
